[global]
log_level = "error"

[mode]
  [mode.clients]
    enabled = true
    refresh = true
    misbehaviour = true

  [mode.connections]
    enabled = true

  [mode.channels]
    enabled = true

  [mode.packets]
    enabled = true
    clear_interval = 100
    clear_on_start = true
    tx_confirmation = true
    auto_register_counterparty_payee = false

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[[chains]]
id = "mars"
type = "CosmosSdk"
ccv_consumer_chain = false
rpc_addr = "http://localhost:26657"
grpc_addr = "http://localhost:9090"
rpc_timeout = "10s"
trusted_node = true
account_prefix = "cosmos"
key_name = "wallet"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 1000000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152
clock_drift = "5s"
max_block_time = "30s"
trusting_period = "14days"
memo_prefix = ""
sequential_batch_tx = false

[chains.gas_price]
denom = "stake"
price = 0.001

[chains.event_source]
batch_delay = "500ms"
mode = "push"
url = "ws://localhost:26657/websocket"

[chains.trust_threshold]
denominator = 3
numerator = 2

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "venus"
type = "CosmosSdk"
ccv_consumer_chain = false
rpc_addr = "http://localhost:26659"
grpc_addr = "http://localhost:9092"
rpc_timeout = "10s"
trusted_node = true
account_prefix = "cosmos"
key_name = "wallet"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 1000000
max_gas = 10000000
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152
clock_drift = "5s"
max_block_time = "30s"
trusting_period = "14days"
memo_prefix = ""
sequential_batch_tx = false

[chains.gas_price]
denom = "stake"
price = 0.001

[chains.event_source]
batch_delay = "500ms"
mode = "push"
url = "ws://localhost:26659/websocket"

[chains.trust_threshold]
denominator = 3
numerator = 2

[chains.address_type]
derivation = "cosmos"
